services:
    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes:
            - ./server/src/:/app/src/
    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db
    client:
        build: ./client
        ports:
            - 8080:3000
        command: npm start
        volumes:
            - ./client/src/:/app/src/
        # hot reload
        environment:
            # le serveur doit se connecter sur localhost
            - WDS_SOCKET=localhost
            # active la lib chokidar pour surveiller les changements
            - CHOKIDAR_USEPOLLING=true
            # active également la surveillance de changements pour watchpack
            - WATCHPACK_POLLING=true
            # "polling" = pollinisation
